# Global config

default:
  ignore: true
  name: boston
  lists:
    - application
    - allocated
    - ice_box
    - scheduled
    - funded
    - passed
    - rejected

# Define teams below

boston: &boston
  listserv: 'iteambos'
  channel: 'iteambos'
  board: '6hD5AVNy'
  lists:
    application: 'Applied at Website'
    allocated: 'Allocated Point Partner'
    ice_box: 'Ice Box'
    scheduled: 'Scheduled to Pitch'
    funded: 'Funded'
    passed: 'Passed - Pitched'
    rejected: 'Passed - No Pitch'

nyc:
  ignore: <%= !Rails.env.production? %>
  listserv: 'iteamnyc'
  channel: 'iteamnyc'
  board: 'WtHewJmA'
  lists:
    application: 'Applied at Website'
    allocated: 'Allocated Point Partner'
    ice_box: 'Waiting for more progress'
    scheduled: 'Scheduled to Pitch'
    funded: 'Invested'
    passed: 'Passed - Pitched'
    rejected: 'Passed - No Pitch'

sf:
  ignore: <%= !Rails.env.production? %>
  listserv: 'iteamsfbay'
  channel: 'iteamsf'
  board: 'lSsw6XnH'
  lists:
    application: 'Applied at Website'
    allocated: 'Needs 1st Meeting'
    ice_box: 'Hold'
    scheduled: 'Ready for partner meeting'
    funded: 'Yes - Money not yet wired'
    passed: 'Passed - Pitched'
    rejected: 'Passed - No Pitch'

phl:
  ignore: <%= !Rails.env.production? %>
  listserv: 'iteamphl'
  channel: 'philly-iteam'
  board: 'GSYLWzGT'
  lists:
    application: 'Applied at Website'
    allocated: 'In Discussions'
    ice_box: 'Deferred / Check-In Later'
    scheduled: 'Pitching'
    funded: 'Invested'
    passed: 'Passed - Pitched'
    rejected: 'Passed - No Pitch'

test:
  <<: *boston
  ignore: <%= !Rails.env.development? %>
  channel: 'bot_tests'
  listserv: 'ym'
